language: node_js

install:
- cd extension; npm install; cd ..

env: # important! Without the top-level env, no job will be allowed to fail.
  - JOB_DEFAULT=test

matrix:
  fast_finish: true
  include:
    - node_js: 8
      env: TYPE=UNIT_CODESTYLE_DEPENDENCY
      script:
      - cd extension
      - npm run test:unit
      - npm run lint
      - npm run check
    - node_js: 8
      env: TYPE=INTEGRATION
      script:
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then echo "${INTEGRATION_CREDENTIALS}" > .integration-credentials.js; fi
      - cd extension
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then npm run test:integration; fi
  allow_failures:
    - node_js: 8
      env: TYPE=INTEGRATION

notifications:
  slack:
    rooms:
      secure: kgEXkOZmi+rPoQhlAk1xnrlDWOqdE+5vhCGYAuZJdk/YU4iskG2FDnDXLiRV5bxJFn+KZzJbKN0/x/Jo55XNhH/RCdAXljF+HDPpH3rgFBziUJv+hvvKrFvkn195G8JMpC8ZIkbiO4+OinMRmAYsCipvBltzEuLTwrP0lD73Rjd3U7gQam44D+nZuu/2+zlps0NW6CjjUvwVXelhT1Ew6BcDmbkfltUMcA0AbqlvXMy3811lZnJaQzVEA1J0Hq3PAMMJWUN/uiNl5gRxIjRE1eiCm1qt9chOpnvSDKG6ycKPf5iMYhcfipk+JQUf9oRU+w6jKx8N3UGHcMeN2O48bGj49agfsvjBbs4SMZ7M3PFU2gmqTx2Dy6nlmpcMtwKQrxTsRY34m+yJQUrx5Sw2++tUUT5Szso02N9WB1m+KiFmPcQaoGRg+DMFwrovofkdZpAm/sxh0p13mKyTdeuA2aEz2Y+9dez6BLDNWDtLC4shJoDpKyYlRBbGsOA7ihFIpwz0FbkVnritzvZa+m5jVWTGxH52DQlHRt77l35NHpEPYP1AhwqL7VDmYBgPCP7IH0tE1OGcNLMrwI2pOATYG+gsfgIIZ0Ud9/lSrlEDDlixeiUMWTnGQADH2lTHBfnnjZk1T3sBbx+Hm7PlO16mqnsWVZvs3k8rhJ+hA5w+dZM=
    on_success: change
    on_failure: always
